# Describe a load balancer

# The service we are balancing
Service = "Calculator"

# The frequency shard states are queried in milliseconds
ShardUpdate = 5000

# URL for hosting the balancer
URL = "localhost:7070"
