# Configure the master coordinator

# Name of the coordinator this field is important because it will be used as a lock
Name = "TestMasterCoordinator"

# Path to run http client
Host = "localhost:4040"
