apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-calculator
spec:
  selector:
    matchLabels:
      app: ms-calculator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms-calculator
    spec:
      containers:
      - image: ms-calculator:0.0.0
        name: ms-calculator
        imagePullPolicy: Never
        resources:
          limits:
            memory: "500M"
            cpu: "50m"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard-calculator
spec:
  selector:
    matchLabels:
      app: shard-calculator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shard-calculator
    spec:
      containers:
      - image: shard-calculator:0.0.0
        name: shard-calculator
        imagePullPolicy: Never
        resources:
          limits:
            memory: "500M"
            cpu: "50m"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ms-calculator
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ms-calculator
---
apiVersion: v1
kind: Service
metadata:
  name: shard-calculator
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: shard-calculator
