# Configure the properties of the gateway service

# Which port on the machine to host the gateway
Port = 8080


[Auth]
    Name = "mstk"
    Password = "mstk123"
    URL = "127.0.0.1:3306"
    DBName = "auth_db"

    TokenLifespan = 60 # Lifespan in minutes
    Secret = "MSTK_API_SECRET_TEST" # API secret for generating JWT tokens
