package templates

// PUBLIC TYPES
// ========================================================================

/*
Data of service template
*/
type UNIXDeployData struct {
	RootDir     string
	ServiceName string
	ServiceLang string
}

/*
Template for deploy scripts for linux
*/
const UnixHeaderDeployTemplate = `#/bin/bash
# THIS IS A AUTOMATIC DEPLOYMENT SCRIPT GENERATED BY WDTK DON'T MODIFY BY HAND ALL CHANGES WILL BE OVERWRITTEN

`

/*
Data of go build template
*/
type GoBuildData struct {
	ServiceName string
	SourceDir   string
	OutDir      string
}

const GoBuildDeployTemplate = `
echo Building {{.ServiceName}}

cd {{.SourceDir}}

echo Running go tidy
if ! go mod tidy
then
	exit 1
fi

echo Downloading dependencies
if ! go get ./
then
	exit 2
fi

echo Building
if ! go build -o {{.OutDir}}{{.ServiceName}} .
then
	exit 3
fi

echo
`

/*
Data of localhost deploy template
*/
type DeployData struct {
	ServiceName string
	Deployment  string
	InFile      string
	OutDir      string
}

const LocalDeployTemplate = `
echo Copying {{.InFile}}
cp ../generated/{{.ServiceName}}_ServiceConfig_{{.Deployment}}.json {{.OutDir}}/ServiceConfig.json
cp {{.InFile}} {{.OutDir}}
`
