package templates

// PUBLIC TYPES
// ========================================================================

/*
Data of service template
*/
type UNIXDeployData struct {
	RootDir     string
	ServiceName string
	ServiceLang string
}

/*
Template for deploy scripts for linux
*/
const UnixHeaderDeployTemplate = `#/bin/bash
# THIS IS A AUTOMATIC DEPLOYMENT SCRIPT GENERATED BY WDTK DON'T MODIFY BY HAND ALL CHANGES WILL BE OVERWRITTEN

`

/*
Data of go build template
*/
type GoBuildData struct {
	ServiceName string
	SourceDir   string
	OutDir      string
}

const GoBuildDeployTemplate = `
echo Building {{.ServiceName}}

cd {{.SourceDir}}

echo Running go tidy
go mod tidy

echo Downloading dependencies
go get ./

echo Building
go build -o {{.OutDir}}{{.ServiceName}} .

echo
`

/*
Data of localhost deploy template
*/
type DeployData struct {
	Deployment string
	InFile     string
	OutDir     string
}

const LocalDeployTemplate = `
echo Copying {{.InFile}}
cp ../generated/ServiceConfig_{{.Deployment}}.json {{.OutDir}}ServiceConfig.json
cp {{.InFile}} {{.OutDir}}
`

/*
Data of localhost deploy template
*/
type WDTKDeployData struct {
	Deployment string
	GatewayDir string
	AuthDir    string
}

const LocalDeployWDTKTemplate = `
echo Copying locator table
cp ../generated/LocatorTable_{{.Deployment}}.json {{.GatewayDir}}LocatorTable.json
cp ../bin/unix/APIGateway {{.GatewayDir}}

echo Copying authentication service
cp ../generated/AuthConfig_{{.Deployment}}.json {{.AuthDir}}AuthConfig.json
cp ../bin/unix/Auth {{.AuthDir}}
`
