package templates

// PUBLIC TYPES
// ========================================================================

/*
Data of service template
*/
type UNIXDeployData struct {
	RootDir      string
	ServiceName  string
	BalancerLang string
	ServiceLang  string
}

/*
Template for deploy scripts for linux
*/
const UnixHeaderDeployTemplate = `#/bin/bash
# THIS IS A AUTOMATIC DEPLOYMENT SCRIPT GENERATED BY WDTK DON'T MODIFY BY HAND ALL CHANGES WILL BE OVERWRITTEN

`

/*
Data of go build template
*/
type GoBuildData struct {
	BuildName   string
	ServiceName string
	SourceDir   string
	OutDir      string
}

const GoBuildDeployTemplate = `
echo Building {{.BuildName}}

cd {{.SourceDir}}

echo Running go tidy
go mod tidy

echo Downloading dependencies
go get ./

echo Building
go build -o {{.OutDir}}{{.ServiceName}}_{{.BuildName}} .

echo
`

/*
Data of localhost deploy template
*/
type DeployData struct {
	InFile string
	OutDir string
}

const LocalDeployTemplate = `
echo Copying {{.InFile}}
cp {{.InFile}} {{.OutDir}}
`
