apiVersion: apps/v1
kind: Deployment
metadata:
  name: mstk-locator
spec:
  selector:
    matchLabels:
      app: mstk-locator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mstk-locator
    spec:
      containers:
      - image: mstk/locator:0.0.0
        name: mstk-locator
        imagePullPolicy: Never
        resources:
          limits:
            memory: "500M"
            cpu: "50m"
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: mstk-project-secret
              key: Secret
---
apiVersion: v1
kind: Service
metadata:
  name: mstk-locator
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mstk-locator
