apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
spec:
  selector:
    matchLabels:
      app: auth-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        resources:
          limits:
            memory: "2Gi"
            cpu: "0.5"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: password
        - name: MYSQL_USER
          value: "mstk"
        - name: MYSQL_DATABASE
          value: "auth_db"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: auth-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: auth-persistent-storage
        persistentVolumeClaim:
          claimName: auth-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: auth-db
  type: LoadBalancer
