apiVersion: v1
kind: PersistentVolume
metadata:
  name: locator-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/locator-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: locator-pv-claim
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
